services:
  app:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - 8081:80
  backend:
    build: 
      context: backend/
    environment:
      - APP_URL=http://ubuntu.orb.local:8000
      - APP_PREFIX=/api/v1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=1
      - DB_NAME=konis
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_DATABASE=konis
  frontend:
    build: 
      context: frontend/
      args:
        VITE_BACKEND_URL: http://ubuntu.orb.local:8081/api/v1

    