services:
  app:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - 8081:80
    networks:
      - webservices
      - default
  backend:
    build: 
      context: backend/
    environment:
      - APP_URL=https://dev.fahrul.id
      - APP_PREFIX=/api/v1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=1
      - DB_NAME=konis
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_DATABASE=konis
  frontend:
    build: 
      context: frontend/
      args:
        VITE_BACKEND_URL: https://dev.fahrul.id/api/v1
networks:
  webservices:
    external: true